### ISSUE TITLE
Menú del programa

### ISSUE THREAD

**Issue by lquintanac** [aigora/twIE_2021-ruleta-2021#2]
Debéis generar código que implemente un **menú provisional** con el que el usuario de vuestro programa debe interactuar. Este menú debe contener las opciones necesarias para acceder a las funcionalidades previstas, aunque aún no realizará ninguna acción. 
El menú estará implementado mediante un bucle `switch-case` y se repetirá indefinidamente hasta que el usuario decida salir del programa.

**Comment by lquintanac** [comment]
Buenas, os falta subir el archivo del menú principal. Una vez subido recordad cerrar esta issue.

**Comment by orgynmobs** [comment]
si ya tenéis el código subido,  cerrad la issue, y la milestone si corresponde
